<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Test</title>
  </head>
  <body>
    <form class="" action="test.php" method="POST">
      <input type="text" name="login" placeholder="login" value="">
      <input type="text" name="password" placeholder="password" value="">
      <button type="button" name="submit">submit</button>
    </form>
    <script src="main.js" ></script>
  </body>
</html>
