<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="stylesheet" href="normalize.css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <title>Tasks JS</title>
  </head>
  <body>
    <main class="container">
      <h1>Task N1</h1>
      <div class="action">
        <p class="text">
        <?= $str ?>
      </div>
      <footer>
        js tasks by Stasiya
      </footer>
      <!--<script src="js/array.js"></script>
      <script src="js/variable.js"></script>
      <script src="js/string.js"></script>
      <script src="js/prompt.js"></script>
      <script src="js/conditions.js"></script>-->

    </main>
  </body>
</html>
