<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="stylesheet" href="normalize.css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <title>Tasks JS</title>
  </head>
  <body>
    <main class="container">
      <h1>Task N1</h1>
      <div class="action">
        <p class="text">
        <!--<?= $sum.', '.$dif.', '.$mult.', '.$div ?>-->
        <!--<?= $text[0].', '.$text[2].', '.$text[4] ?>-->
        <!--<?= 'Kоличество секунд в часе: <b>'.$sec_hour.'</b>, количество секунд в сутках: <b>'.$sec_day.'</b>, количество секунд в месяце: <b>'.$sec_month.'</b>' ?>
        <?= $hour.':'.$min.':'.$sec?>
        <?= $var ?>-->
        <!-- ARRAYS -->
        <!--<?= 'Зарплата Пети: '.$salaryP?><br>
        <?= 'Зарплата Коли: '.$salaryN?>

        <?= 'Today is '.$today.'!'?>

        <?= $joomla.', '.$drupal.', '.$green.', '.$red?>-->

        <?= $result?><br>


      <footer>
        js tasks by Stasiya
      </footer>
      <!--<script src="js/array.js"></script>
      <script src="js/variable.js"></script>
      <script src="js/string.js"></script>
      <script src="js/prompt.js"></script>
      <script src="js/conditions.js"></script>-->

    </main>
  </body>
</html>
